#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="classroom")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertschedule(schedule instance);
  partial void Updateschedule(schedule instance);
  partial void Deleteschedule(schedule instance);
  partial void Insertuser_login(user_login instance);
  partial void Updateuser_login(user_login instance);
  partial void Deleteuser_login(user_login instance);
  partial void InsertEducator(Educator instance);
  partial void UpdateEducator(Educator instance);
  partial void DeleteEducator(Educator instance);
  partial void InsertStudent(Student instance);
  partial void UpdateStudent(Student instance);
  partial void DeleteStudent(Student instance);
  partial void Inserte_class(e_class instance);
  partial void Updatee_class(e_class instance);
  partial void Deletee_class(e_class instance);
  partial void InsertInvitation_data(Invitation_data instance);
  partial void UpdateInvitation_data(Invitation_data instance);
  partial void DeleteInvitation_data(Invitation_data instance);
  partial void Insertgroupformed(groupformed instance);
  partial void Updategroupformed(groupformed instance);
  partial void Deletegroupformed(groupformed instance);
  partial void Insertgroupdata(groupdata instance);
  partial void Updategroupdata(groupdata instance);
  partial void Deletegroupdata(groupdata instance);
  partial void Insertstudent_class(student_class instance);
  partial void Updatestudent_class(student_class instance);
  partial void Deletestudent_class(student_class instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<schedule> schedules
	{
		get
		{
			return this.GetTable<schedule>();
		}
	}
	
	public System.Data.Linq.Table<user_login> user_logins
	{
		get
		{
			return this.GetTable<user_login>();
		}
	}
	
	public System.Data.Linq.Table<Educator> Educators
	{
		get
		{
			return this.GetTable<Educator>();
		}
	}
	
	public System.Data.Linq.Table<Student> Students
	{
		get
		{
			return this.GetTable<Student>();
		}
	}
	
	public System.Data.Linq.Table<e_class> e_classes
	{
		get
		{
			return this.GetTable<e_class>();
		}
	}
	
	public System.Data.Linq.Table<Invitation_data> Invitation_datas
	{
		get
		{
			return this.GetTable<Invitation_data>();
		}
	}
	
	public System.Data.Linq.Table<groupformed> groupformeds
	{
		get
		{
			return this.GetTable<groupformed>();
		}
	}
	
	public System.Data.Linq.Table<groupdata> groupdatas
	{
		get
		{
			return this.GetTable<groupdata>();
		}
	}
	
	public System.Data.Linq.Table<student_class> student_classes
	{
		get
		{
			return this.GetTable<student_class>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.schedule")]
public partial class schedule : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private System.Nullable<int> _class_id;
	
	private string _sdate;
	
	private string _stime;
	
	private string _etime;
	
	private string _location;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onclass_idChanging(System.Nullable<int> value);
    partial void Onclass_idChanged();
    partial void OnsdateChanging(string value);
    partial void OnsdateChanged();
    partial void OnstimeChanging(string value);
    partial void OnstimeChanged();
    partial void OnetimeChanging(string value);
    partial void OnetimeChanged();
    partial void OnlocationChanging(string value);
    partial void OnlocationChanged();
    #endregion
	
	public schedule()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_class_id", DbType="Int")]
	public System.Nullable<int> class_id
	{
		get
		{
			return this._class_id;
		}
		set
		{
			if ((this._class_id != value))
			{
				this.Onclass_idChanging(value);
				this.SendPropertyChanging();
				this._class_id = value;
				this.SendPropertyChanged("class_id");
				this.Onclass_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdate", DbType="VarChar(50)")]
	public string sdate
	{
		get
		{
			return this._sdate;
		}
		set
		{
			if ((this._sdate != value))
			{
				this.OnsdateChanging(value);
				this.SendPropertyChanging();
				this._sdate = value;
				this.SendPropertyChanged("sdate");
				this.OnsdateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stime", DbType="VarChar(50)")]
	public string stime
	{
		get
		{
			return this._stime;
		}
		set
		{
			if ((this._stime != value))
			{
				this.OnstimeChanging(value);
				this.SendPropertyChanging();
				this._stime = value;
				this.SendPropertyChanged("stime");
				this.OnstimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etime", DbType="VarChar(50)")]
	public string etime
	{
		get
		{
			return this._etime;
		}
		set
		{
			if ((this._etime != value))
			{
				this.OnetimeChanging(value);
				this.SendPropertyChanging();
				this._etime = value;
				this.SendPropertyChanged("etime");
				this.OnetimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location", DbType="VarChar(50)")]
	public string location
	{
		get
		{
			return this._location;
		}
		set
		{
			if ((this._location != value))
			{
				this.OnlocationChanging(value);
				this.SendPropertyChanging();
				this._location = value;
				this.SendPropertyChanged("location");
				this.OnlocationChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.user_login")]
public partial class user_login : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _emailid;
	
	private string _username;
	
	private string _password;
	
	private System.Nullable<int> _type;
	
	private System.Nullable<int> _uid;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnemailidChanging(string value);
    partial void OnemailidChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OntypeChanging(System.Nullable<int> value);
    partial void OntypeChanged();
    partial void OnuidChanging(System.Nullable<int> value);
    partial void OnuidChanged();
    #endregion
	
	public user_login()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailid", DbType="VarChar(50)")]
	public string emailid
	{
		get
		{
			return this._emailid;
		}
		set
		{
			if ((this._emailid != value))
			{
				this.OnemailidChanging(value);
				this.SendPropertyChanging();
				this._emailid = value;
				this.SendPropertyChanged("emailid");
				this.OnemailidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50)")]
	public string username
	{
		get
		{
			return this._username;
		}
		set
		{
			if ((this._username != value))
			{
				this.OnusernameChanging(value);
				this.SendPropertyChanging();
				this._username = value;
				this.SendPropertyChanged("username");
				this.OnusernameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50)")]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Int")]
	public System.Nullable<int> type
	{
		get
		{
			return this._type;
		}
		set
		{
			if ((this._type != value))
			{
				this.OntypeChanging(value);
				this.SendPropertyChanging();
				this._type = value;
				this.SendPropertyChanged("type");
				this.OntypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", DbType="Int")]
	public System.Nullable<int> uid
	{
		get
		{
			return this._uid;
		}
		set
		{
			if ((this._uid != value))
			{
				this.OnuidChanging(value);
				this.SendPropertyChanging();
				this._uid = value;
				this.SendPropertyChanged("uid");
				this.OnuidChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Educator")]
public partial class Educator : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _eid;
	
	private string _fname;
	
	private string _lname;
	
	private string _Collage;
	
	private string _position;
	
	private string _state;
	
	private string _city;
	
	private string _contactno;
	
	private string _emailid;
	
	private string _imagepath;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OneidChanging(int value);
    partial void OneidChanged();
    partial void OnfnameChanging(string value);
    partial void OnfnameChanged();
    partial void OnlnameChanging(string value);
    partial void OnlnameChanged();
    partial void OnCollageChanging(string value);
    partial void OnCollageChanged();
    partial void OnpositionChanging(string value);
    partial void OnpositionChanged();
    partial void OnstateChanging(string value);
    partial void OnstateChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OncontactnoChanging(string value);
    partial void OncontactnoChanged();
    partial void OnemailidChanging(string value);
    partial void OnemailidChanged();
    partial void OnimagepathChanging(string value);
    partial void OnimagepathChanged();
    #endregion
	
	public Educator()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int eid
	{
		get
		{
			return this._eid;
		}
		set
		{
			if ((this._eid != value))
			{
				this.OneidChanging(value);
				this.SendPropertyChanging();
				this._eid = value;
				this.SendPropertyChanged("eid");
				this.OneidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fname", DbType="VarChar(50)")]
	public string fname
	{
		get
		{
			return this._fname;
		}
		set
		{
			if ((this._fname != value))
			{
				this.OnfnameChanging(value);
				this.SendPropertyChanging();
				this._fname = value;
				this.SendPropertyChanged("fname");
				this.OnfnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lname", DbType="VarChar(50)")]
	public string lname
	{
		get
		{
			return this._lname;
		}
		set
		{
			if ((this._lname != value))
			{
				this.OnlnameChanging(value);
				this.SendPropertyChanging();
				this._lname = value;
				this.SendPropertyChanged("lname");
				this.OnlnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Collage", DbType="VarChar(50)")]
	public string Collage
	{
		get
		{
			return this._Collage;
		}
		set
		{
			if ((this._Collage != value))
			{
				this.OnCollageChanging(value);
				this.SendPropertyChanging();
				this._Collage = value;
				this.SendPropertyChanged("Collage");
				this.OnCollageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_position", DbType="VarChar(30)")]
	public string position
	{
		get
		{
			return this._position;
		}
		set
		{
			if ((this._position != value))
			{
				this.OnpositionChanging(value);
				this.SendPropertyChanging();
				this._position = value;
				this.SendPropertyChanged("position");
				this.OnpositionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="VarChar(30)")]
	public string state
	{
		get
		{
			return this._state;
		}
		set
		{
			if ((this._state != value))
			{
				this.OnstateChanging(value);
				this.SendPropertyChanging();
				this._state = value;
				this.SendPropertyChanged("state");
				this.OnstateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(30)")]
	public string city
	{
		get
		{
			return this._city;
		}
		set
		{
			if ((this._city != value))
			{
				this.OncityChanging(value);
				this.SendPropertyChanging();
				this._city = value;
				this.SendPropertyChanged("city");
				this.OncityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contactno", DbType="VarChar(50)")]
	public string contactno
	{
		get
		{
			return this._contactno;
		}
		set
		{
			if ((this._contactno != value))
			{
				this.OncontactnoChanging(value);
				this.SendPropertyChanging();
				this._contactno = value;
				this.SendPropertyChanged("contactno");
				this.OncontactnoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailid", DbType="VarChar(50)")]
	public string emailid
	{
		get
		{
			return this._emailid;
		}
		set
		{
			if ((this._emailid != value))
			{
				this.OnemailidChanging(value);
				this.SendPropertyChanging();
				this._emailid = value;
				this.SendPropertyChanged("emailid");
				this.OnemailidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imagepath", DbType="VarChar(MAX)")]
	public string imagepath
	{
		get
		{
			return this._imagepath;
		}
		set
		{
			if ((this._imagepath != value))
			{
				this.OnimagepathChanging(value);
				this.SendPropertyChanging();
				this._imagepath = value;
				this.SendPropertyChanged("imagepath");
				this.OnimagepathChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Student")]
public partial class Student : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _rid;
	
	private string _fname;
	
	private string _lname;
	
	private string _Collage;
	
	private string _state;
	
	private string _city;
	
	private string _contactno;
	
	private string _emailid;
	
	private string _imagepath;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnridChanging(int value);
    partial void OnridChanged();
    partial void OnfnameChanging(string value);
    partial void OnfnameChanged();
    partial void OnlnameChanging(string value);
    partial void OnlnameChanged();
    partial void OnCollageChanging(string value);
    partial void OnCollageChanged();
    partial void OnstateChanging(string value);
    partial void OnstateChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OncontactnoChanging(string value);
    partial void OncontactnoChanged();
    partial void OnemailidChanging(string value);
    partial void OnemailidChanged();
    partial void OnimagepathChanging(string value);
    partial void OnimagepathChanged();
    #endregion
	
	public Student()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int rid
	{
		get
		{
			return this._rid;
		}
		set
		{
			if ((this._rid != value))
			{
				this.OnridChanging(value);
				this.SendPropertyChanging();
				this._rid = value;
				this.SendPropertyChanged("rid");
				this.OnridChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fname", DbType="VarChar(50)")]
	public string fname
	{
		get
		{
			return this._fname;
		}
		set
		{
			if ((this._fname != value))
			{
				this.OnfnameChanging(value);
				this.SendPropertyChanging();
				this._fname = value;
				this.SendPropertyChanged("fname");
				this.OnfnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lname", DbType="VarChar(50)")]
	public string lname
	{
		get
		{
			return this._lname;
		}
		set
		{
			if ((this._lname != value))
			{
				this.OnlnameChanging(value);
				this.SendPropertyChanging();
				this._lname = value;
				this.SendPropertyChanged("lname");
				this.OnlnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Collage", DbType="VarChar(50)")]
	public string Collage
	{
		get
		{
			return this._Collage;
		}
		set
		{
			if ((this._Collage != value))
			{
				this.OnCollageChanging(value);
				this.SendPropertyChanging();
				this._Collage = value;
				this.SendPropertyChanged("Collage");
				this.OnCollageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="VarChar(30)")]
	public string state
	{
		get
		{
			return this._state;
		}
		set
		{
			if ((this._state != value))
			{
				this.OnstateChanging(value);
				this.SendPropertyChanging();
				this._state = value;
				this.SendPropertyChanged("state");
				this.OnstateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(30)")]
	public string city
	{
		get
		{
			return this._city;
		}
		set
		{
			if ((this._city != value))
			{
				this.OncityChanging(value);
				this.SendPropertyChanging();
				this._city = value;
				this.SendPropertyChanged("city");
				this.OncityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contactno", DbType="VarChar(50)")]
	public string contactno
	{
		get
		{
			return this._contactno;
		}
		set
		{
			if ((this._contactno != value))
			{
				this.OncontactnoChanging(value);
				this.SendPropertyChanging();
				this._contactno = value;
				this.SendPropertyChanged("contactno");
				this.OncontactnoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailid", DbType="VarChar(50)")]
	public string emailid
	{
		get
		{
			return this._emailid;
		}
		set
		{
			if ((this._emailid != value))
			{
				this.OnemailidChanging(value);
				this.SendPropertyChanging();
				this._emailid = value;
				this.SendPropertyChanged("emailid");
				this.OnemailidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imagepath", DbType="VarChar(MAX)")]
	public string imagepath
	{
		get
		{
			return this._imagepath;
		}
		set
		{
			if ((this._imagepath != value))
			{
				this.OnimagepathChanging(value);
				this.SendPropertyChanging();
				this._imagepath = value;
				this.SendPropertyChanged("imagepath");
				this.OnimagepathChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.e_class")]
public partial class e_class : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _classid;
	
	private System.Nullable<int> _eid;
	
	private string _course;
	
	private string _description;
	
	private string _Location;
	
	private System.Nullable<int> _member;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnclassidChanging(int value);
    partial void OnclassidChanged();
    partial void OneidChanging(System.Nullable<int> value);
    partial void OneidChanged();
    partial void OncourseChanging(string value);
    partial void OncourseChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    partial void OnmemberChanging(System.Nullable<int> value);
    partial void OnmemberChanged();
    #endregion
	
	public e_class()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_classid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int classid
	{
		get
		{
			return this._classid;
		}
		set
		{
			if ((this._classid != value))
			{
				this.OnclassidChanging(value);
				this.SendPropertyChanging();
				this._classid = value;
				this.SendPropertyChanged("classid");
				this.OnclassidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eid", DbType="Int")]
	public System.Nullable<int> eid
	{
		get
		{
			return this._eid;
		}
		set
		{
			if ((this._eid != value))
			{
				this.OneidChanging(value);
				this.SendPropertyChanging();
				this._eid = value;
				this.SendPropertyChanged("eid");
				this.OneidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_course", DbType="VarChar(100)")]
	public string course
	{
		get
		{
			return this._course;
		}
		set
		{
			if ((this._course != value))
			{
				this.OncourseChanging(value);
				this.SendPropertyChanging();
				this._course = value;
				this.SendPropertyChanged("course");
				this.OncourseChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(MAX)")]
	public string description
	{
		get
		{
			return this._description;
		}
		set
		{
			if ((this._description != value))
			{
				this.OndescriptionChanging(value);
				this.SendPropertyChanging();
				this._description = value;
				this.SendPropertyChanged("description");
				this.OndescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="VarChar(50)")]
	public string Location
	{
		get
		{
			return this._Location;
		}
		set
		{
			if ((this._Location != value))
			{
				this.OnLocationChanging(value);
				this.SendPropertyChanging();
				this._Location = value;
				this.SendPropertyChanged("Location");
				this.OnLocationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_member", DbType="Int")]
	public System.Nullable<int> member
	{
		get
		{
			return this._member;
		}
		set
		{
			if ((this._member != value))
			{
				this.OnmemberChanging(value);
				this.SendPropertyChanging();
				this._member = value;
				this.SendPropertyChanged("member");
				this.OnmemberChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Invitation_data")]
public partial class Invitation_data : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _iid;
	
	private System.Nullable<int> _eid;
	
	private System.Nullable<int> _sid;
	
	private System.Nullable<System.DateTime> _date;
	
	private string _status;
	
	private System.Nullable<int> _classid;
	
	private string _message;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OniidChanging(int value);
    partial void OniidChanged();
    partial void OneidChanging(System.Nullable<int> value);
    partial void OneidChanged();
    partial void OnsidChanging(System.Nullable<int> value);
    partial void OnsidChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void OnclassidChanging(System.Nullable<int> value);
    partial void OnclassidChanged();
    partial void OnmessageChanging(string value);
    partial void OnmessageChanged();
    #endregion
	
	public Invitation_data()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int iid
	{
		get
		{
			return this._iid;
		}
		set
		{
			if ((this._iid != value))
			{
				this.OniidChanging(value);
				this.SendPropertyChanging();
				this._iid = value;
				this.SendPropertyChanged("iid");
				this.OniidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eid", DbType="Int")]
	public System.Nullable<int> eid
	{
		get
		{
			return this._eid;
		}
		set
		{
			if ((this._eid != value))
			{
				this.OneidChanging(value);
				this.SendPropertyChanging();
				this._eid = value;
				this.SendPropertyChanged("eid");
				this.OneidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sid", DbType="Int")]
	public System.Nullable<int> sid
	{
		get
		{
			return this._sid;
		}
		set
		{
			if ((this._sid != value))
			{
				this.OnsidChanging(value);
				this.SendPropertyChanging();
				this._sid = value;
				this.SendPropertyChanged("sid");
				this.OnsidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="Date")]
	public System.Nullable<System.DateTime> date
	{
		get
		{
			return this._date;
		}
		set
		{
			if ((this._date != value))
			{
				this.OndateChanging(value);
				this.SendPropertyChanging();
				this._date = value;
				this.SendPropertyChanged("date");
				this.OndateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(50)")]
	public string status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_classid", DbType="Int")]
	public System.Nullable<int> classid
	{
		get
		{
			return this._classid;
		}
		set
		{
			if ((this._classid != value))
			{
				this.OnclassidChanging(value);
				this.SendPropertyChanging();
				this._classid = value;
				this.SendPropertyChanged("classid");
				this.OnclassidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_message", DbType="VarChar(MAX)")]
	public string message
	{
		get
		{
			return this._message;
		}
		set
		{
			if ((this._message != value))
			{
				this.OnmessageChanging(value);
				this.SendPropertyChanging();
				this._message = value;
				this.SendPropertyChanged("message");
				this.OnmessageChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.groupformed")]
public partial class groupformed : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _gi;
	
	private System.Nullable<int> _gid;
	
	private string _sid;
	
	private string _status;
	
	private EntityRef<groupformed> _groupformed2;
	
	private EntityRef<groupformed> _groupformed1;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OngiChanging(int value);
    partial void OngiChanged();
    partial void OngidChanging(System.Nullable<int> value);
    partial void OngidChanged();
    partial void OnsidChanging(string value);
    partial void OnsidChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    #endregion
	
	public groupformed()
	{
		this._groupformed2 = default(EntityRef<groupformed>);
		this._groupformed1 = default(EntityRef<groupformed>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gi", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int gi
	{
		get
		{
			return this._gi;
		}
		set
		{
			if ((this._gi != value))
			{
				if (this._groupformed1.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OngiChanging(value);
				this.SendPropertyChanging();
				this._gi = value;
				this.SendPropertyChanged("gi");
				this.OngiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gid", DbType="Int")]
	public System.Nullable<int> gid
	{
		get
		{
			return this._gid;
		}
		set
		{
			if ((this._gid != value))
			{
				this.OngidChanging(value);
				this.SendPropertyChanging();
				this._gid = value;
				this.SendPropertyChanged("gid");
				this.OngidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sid", DbType="VarChar(50)")]
	public string sid
	{
		get
		{
			return this._sid;
		}
		set
		{
			if ((this._sid != value))
			{
				this.OnsidChanging(value);
				this.SendPropertyChanging();
				this._sid = value;
				this.SendPropertyChanged("sid");
				this.OnsidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(50)")]
	public string status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="groupformed_groupformed", Storage="_groupformed2", ThisKey="gi", OtherKey="gi", IsUnique=true, IsForeignKey=false)]
	public groupformed groupformed2
	{
		get
		{
			return this._groupformed2.Entity;
		}
		set
		{
			groupformed previousValue = this._groupformed2.Entity;
			if (((previousValue != value) 
						|| (this._groupformed2.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._groupformed2.Entity = null;
					previousValue.groupformed1 = null;
				}
				this._groupformed2.Entity = value;
				if ((value != null))
				{
					value.groupformed1 = this;
				}
				this.SendPropertyChanged("groupformed2");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="groupformed_groupformed", Storage="_groupformed1", ThisKey="gi", OtherKey="gi", IsForeignKey=true)]
	public groupformed groupformed1
	{
		get
		{
			return this._groupformed1.Entity;
		}
		set
		{
			groupformed previousValue = this._groupformed1.Entity;
			if (((previousValue != value) 
						|| (this._groupformed1.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._groupformed1.Entity = null;
					previousValue.groupformed2 = null;
				}
				this._groupformed1.Entity = value;
				if ((value != null))
				{
					value.groupformed2 = this;
					this._gi = value.gi;
				}
				else
				{
					this._gi = default(int);
				}
				this.SendPropertyChanged("groupformed1");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.groupdata")]
public partial class groupdata : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _gid;
	
	private string _gname;
	
	private string _creator;
	
	private string _Description;
	
	private System.Nullable<System.DateTime> _date;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OngidChanging(int value);
    partial void OngidChanged();
    partial void OngnameChanging(string value);
    partial void OngnameChanged();
    partial void OncreatorChanging(string value);
    partial void OncreatorChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    #endregion
	
	public groupdata()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int gid
	{
		get
		{
			return this._gid;
		}
		set
		{
			if ((this._gid != value))
			{
				this.OngidChanging(value);
				this.SendPropertyChanging();
				this._gid = value;
				this.SendPropertyChanged("gid");
				this.OngidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gname", DbType="VarChar(50)")]
	public string gname
	{
		get
		{
			return this._gname;
		}
		set
		{
			if ((this._gname != value))
			{
				this.OngnameChanging(value);
				this.SendPropertyChanging();
				this._gname = value;
				this.SendPropertyChanged("gname");
				this.OngnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creator", DbType="VarChar(50)")]
	public string creator
	{
		get
		{
			return this._creator;
		}
		set
		{
			if ((this._creator != value))
			{
				this.OncreatorChanging(value);
				this.SendPropertyChanging();
				this._creator = value;
				this.SendPropertyChanged("creator");
				this.OncreatorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(MAX)")]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this.OnDescriptionChanging(value);
				this.SendPropertyChanging();
				this._Description = value;
				this.SendPropertyChanged("Description");
				this.OnDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="Date")]
	public System.Nullable<System.DateTime> date
	{
		get
		{
			return this._date;
		}
		set
		{
			if ((this._date != value))
			{
				this.OndateChanging(value);
				this.SendPropertyChanging();
				this._date = value;
				this.SendPropertyChanged("date");
				this.OndateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.student_class")]
public partial class student_class : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _classid;
	
	private System.Nullable<int> _sid;
	
	private System.Nullable<int> _eid;
	
	private string _cid;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnclassidChanging(int value);
    partial void OnclassidChanged();
    partial void OnsidChanging(System.Nullable<int> value);
    partial void OnsidChanged();
    partial void OneidChanging(System.Nullable<int> value);
    partial void OneidChanged();
    partial void OncidChanging(string value);
    partial void OncidChanged();
    #endregion
	
	public student_class()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_classid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int classid
	{
		get
		{
			return this._classid;
		}
		set
		{
			if ((this._classid != value))
			{
				this.OnclassidChanging(value);
				this.SendPropertyChanging();
				this._classid = value;
				this.SendPropertyChanged("classid");
				this.OnclassidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sid", DbType="Int")]
	public System.Nullable<int> sid
	{
		get
		{
			return this._sid;
		}
		set
		{
			if ((this._sid != value))
			{
				this.OnsidChanging(value);
				this.SendPropertyChanging();
				this._sid = value;
				this.SendPropertyChanged("sid");
				this.OnsidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eid", DbType="Int")]
	public System.Nullable<int> eid
	{
		get
		{
			return this._eid;
		}
		set
		{
			if ((this._eid != value))
			{
				this.OneidChanging(value);
				this.SendPropertyChanging();
				this._eid = value;
				this.SendPropertyChanged("eid");
				this.OneidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cid", DbType="NChar(10)")]
	public string cid
	{
		get
		{
			return this._cid;
		}
		set
		{
			if ((this._cid != value))
			{
				this.OncidChanging(value);
				this.SendPropertyChanging();
				this._cid = value;
				this.SendPropertyChanged("cid");
				this.OncidChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
